In [1]:
import statsmodels.api as sm

In [9]:
X = [1,2,3,4,5]
y = [5,9,13,17,21]

In [10]:
X = sm.add_constant(X)

In [11]:
model = sm.OLS(y,X)

In [12]:
results = model.fit()

In [13]:
results.params

array([1., 4.])

In [14]:
results.pvalues

array([2.13974900e-43, 9.16418463e-47])

In [32]:
import statsmodels.api as sm

X = [1,2,3,4,5]
y = [1,1,1,1,1]

X = sm.add_constant(X)

model = sm.OLS(y,X)

results = model.fit()


In [33]:
results.params

array([1.00000000e+00, 5.55111512e-17])

In [34]:
results.pvalues

array([3.14067943e-47, 5.02753909e-01])

In [87]:
import statsmodels.api as sm

X_giv = [4,7,6,2,3]#Diet score
y_giv = [27,29,23,20,21]#Body Mass Index (BMI)

X = sm.add_constant(X_giv)

model = sm.OLS(y_giv,X)

results = model.fit()
results.params

array([17.86046512,  1.39534884])

In [88]:
import plotly.graph_objects as go

In [89]:
fig = go.Figure(data=go.Scatter(x=X_giv,y=y,mode="markers",name="Give"))

In [90]:
fig.add_scatter(x=X_giv,y=results.fittedvalues,name="Model")

In [96]:
import pandas as pa

In [92]:
data = {"DietScore":[4,7,6,2,3],"Male":[0,1,1,0,0],"Age>20":[1,1,0,0,1],"BMI":[27,29,23,20,21]}

In [93]:
bmi_score_df = pa.DataFrame(data)

In [94]:
X_giv = bmi_score_df[["DietScore","Male","Age>20"]]
y_giv = bmi_score_df["BMI"]#Body Mass Index (BMI)

X = sm.add_constant(X_giv)

model = sm.OLS(y_giv,X)

results = model.fit()

In [95]:
results.params

const         9.25
DietScore     4.75
Male        -13.50
Age>20       -1.25
dtype: float64

In [97]:
real_estate_data = pa.read_csv("RealEstate.csv")

In [98]:
real_estate_data

No  X1 transaction date  X2 house age  ...  X5 latitude  X6 longitude  Y house price of unit area
0      1             2012.917          32.0  ...     24.98298     121.54024                        37.9
1      2             2012.917          19.5  ...     24.98034     121.53951                        42.2
2      3             2013.583          13.3  ...     24.98746     121.54391                        47.3
3      4             2013.500          13.3  ...     24.98746     121.54391                        54.8
4      5             2012.833           5.0  ...     24.97937     121.54245                        43.1
..   ...                  ...           ...  ...          ...           ...                         ...
409  410             2013.000          13.7  ...     24.94155     121.50381                        15.4
410  411             2012.667           5.6  ...     24.97433     121.54310                        50.0
411  412             2013.250          18.8  ...     24.97923     121.53986                        40.6
412  413             2013.000           8.1  ...     24.96674     121.54067                        52.5
413  414             2013.500           6.5  ...     24.97433     121.54310                        63.9

[414 rows x 8 columns]

In [100]:
X = real_estate_data[["X1 transaction date",
                     "X2 house age","X3 distance to the nearest MRT station",
                      "X4 number of convenience stores",
                      "X5 latitude","X6 longitude"]]

In [101]:
y = real_estate_data["Y house price of unit area"]

In [102]:
import statsmodels.api as sm

In [103]:
X = sm.add_constant(X)

In [104]:
model = sm.OLS(y,X)

In [105]:
results = model.fit()

In [106]:
results.pvalues

const                                     3.371059e-02
X1 transaction date                       1.033686e-03
X2 house age                              1.064969e-11
X3 distance to the nearest MRT station    1.038560e-09
X4 number of convenience stores           3.835416e-09
X5 latitude                               6.383415e-07
X6 longitude                              7.982928e-01
dtype: float64

In [108]:
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                OLS Regression Results                                
======================================================================================
Dep. Variable:     Y house price of unit area   R-squared:                       0.582
Model:                                    OLS   Adj. R-squared:                  0.576
Method:                         Least Squares   F-statistic:                     94.59
Date:                        Tue, 04 Jul 2023   Prob (F-statistic):           4.86e-74
Time:                                18:49:02   Log-Likelihood:                -1487.0
No. Observations:                         414   AIC:                             2988.
Df Residuals:                             407   BIC:                             3016.
Df Model:                                   6                                         
Covariance Type:                    nonrobust                                         
==========================================================================================================
                                             coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------------------
const                                  -1.444e+04   6775.671     -2.131      0.034   -2.78e+04   -1117.421
X1 transaction date                        5.1462      1.557      3.305      0.001       2.085       8.207
X2 house age                              -0.2697      0.039     -7.000      0.000      -0.345      -0.194
X3 distance to the nearest MRT station    -0.0045      0.001     -6.250      0.000      -0.006      -0.003
X4 number of convenience stores            1.1333      0.188      6.023      0.000       0.763       1.503
X5 latitude                              225.4730     44.567      5.059      0.000     137.863     313.083
X6 longitude                             -12.4236     48.582     -0.256      0.798    -107.927      83.079
==============================================================================
Omnibus:                      231.634   Durbin-Watson:                   2.153
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             3599.138
Skew:                           2.026   Prob(JB):                         0.00
Kurtosis:                      16.865   Cond. No.                     3.72e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.72e+07. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [115]:
X = real_estate_data[["X1 transaction date",
                     "X2 house age","X3 distance to the nearest MRT station",
                      "X4 number of convenience stores",
                      "X5 latitude"]]

y = real_estate_data["Y house price of unit area"]

X = sm.add_constant(X)

model = sm.OLS(y,X)

results = model.fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                OLS Regression Results                                
======================================================================================
Dep. Variable:     Y house price of unit area   R-squared:                       0.582
Model:                                    OLS   Adj. R-squared:                  0.577
Method:                         Least Squares   F-statistic:                     113.8
Date:                        Tue, 04 Jul 2023   Prob (F-statistic):           4.47e-75
Time:                                19:13:21   Log-Likelihood:                -1487.0
No. Observations:                         414   AIC:                             2986.
Df Residuals:                             408   BIC:                             3010.
Df Model:                                   5                                         
Covariance Type:                    nonrobust                                         
==========================================================================================================
                                             coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------------------
const                                  -1.596e+04   3233.450     -4.936      0.000   -2.23e+04   -9602.961
X1 transaction date                        5.1348      1.555      3.303      0.001       2.079       8.191
X2 house age                              -0.2694      0.038     -7.003      0.000      -0.345      -0.194
X3 distance to the nearest MRT station    -0.0044      0.000     -8.887      0.000      -0.005      -0.003
X4 number of convenience stores            1.1361      0.188      6.056      0.000       0.767       1.505
X5 latitude                              226.8816     44.174      5.136      0.000     140.044     313.719
==============================================================================
Omnibus:                      232.810   Durbin-Watson:                   2.154
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             3644.713
Skew:                           2.038   Prob(JB):                         0.00
Kurtosis:                      16.953   Cond. No.                     1.77e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.77e+07. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [110]:
X = real_estate_data[["X1 transaction date",
                     "X2 house age","X3 distance to the nearest MRT station",
                      "X4 number of convenience stores"]]

y = real_estate_data["Y house price of unit area"]

X = sm.add_constant(X)

model = sm.OLS(y,X)

results = model.fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                OLS Regression Results                                
======================================================================================
Dep. Variable:     Y house price of unit area   R-squared:                       0.555
Model:                                    OLS   Adj. R-squared:                  0.551
Method:                         Least Squares   F-statistic:                     127.7
Date:                        Tue, 04 Jul 2023   Prob (F-statistic):           1.23e-70
Time:                                18:59:31   Log-Likelihood:                -1500.0
No. Observations:                         414   AIC:                             3010.
Df Residuals:                             409   BIC:                             3030.
Df Model:                                   4                                         
Covariance Type:                    nonrobust                                         
==========================================================================================================
                                             coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------------------
const                                  -1.159e+04   3214.797     -3.605      0.000   -1.79e+04   -5269.161
X1 transaction date                        5.7780      1.597      3.618      0.000       2.639       8.917
X2 house age                              -0.2545      0.040     -6.438      0.000      -0.332      -0.177
X3 distance to the nearest MRT station    -0.0055      0.000    -12.305      0.000      -0.006      -0.005
X4 number of convenience stores            1.2579      0.192      6.558      0.000       0.881       1.635
==============================================================================
Omnibus:                      214.129   Durbin-Watson:                   2.115
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             2979.678
Skew:                           1.855   Prob(JB):                         0.00
Kurtosis:                      15.609   Cond. No.                     1.71e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.71e+07. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [112]:
X = real_estate_data[["X1 transaction date",
                     "X2 house age","X3 distance to the nearest MRT station",
                      "X4 number of convenience stores"]]

y = real_estate_data["Y house price of unit area"]

X = sm.add_constant(X)

model = sm.OLS(y,X)

results = model.fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                OLS Regression Results                                
======================================================================================
Dep. Variable:     Y house price of unit area   R-squared:                       0.509
Model:                                    OLS   Adj. R-squared:                  0.505
Method:                         Least Squares   F-statistic:                     141.4
Date:                        Tue, 04 Jul 2023   Prob (F-statistic):           6.60e-63
Time:                                19:00:04   Log-Likelihood:                -1520.7
No. Observations:                         414   AIC:                             3049.
Df Residuals:                             410   BIC:                             3065.
Df Model:                                   3                                         
Covariance Type:                    nonrobust                                         
==========================================================================================================
                                             coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------------------
const                                  -1.278e+04   3370.050     -3.794      0.000   -1.94e+04   -6159.776
X1 transaction date                        6.3754      1.674      3.808      0.000       3.085       9.666
X2 house age                              -0.2336      0.041     -5.645      0.000      -0.315      -0.152
X3 distance to the nearest MRT station    -0.0073      0.000    -19.501      0.000      -0.008      -0.007
==============================================================================
Omnibus:                      153.194   Durbin-Watson:                   2.117
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1245.762
Skew:                           1.348   Prob(JB):                    3.06e-271
Kurtosis:                      11.059   Cond. No.                     1.71e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.71e+07. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [142]:
#Results with 5 factors used

import plotly.figure_factory as ff
import numpy as np

sd = np.std([results.resid])
norm_dat = np.random.normal(0,sd,10000)


fig = ff.create_distplot([results.resid,norm_dat],["Residuals","Normal distribution(0,sigma)"])

fig.show()

In [143]:
import math
import numpy as np
from scipy.stats import shapiro 
from scipy.stats import lognorm


#perform Shapiro-Wilk test for normality
shapiro(results.resid)

ShapiroResult(statistic=0.8755013942718506, pvalue=9.746885879032814e-18)